config/routes.rb
Rails.application.routes.draw do
  root to: 'tops#index'
  resources :posts do
    resources :likes, only: [:create, :destroy]
    collection do
      post :confirm
    end
  end
  resources :sessions, only:[:new, :create, :destroy]
  resources :users, only: [:new, :create, :show, :likes] do
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  counter_culture :post
  validates :user_id, presence: true
  validates :post_id, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :objective, presence: true, length: { maximum: 50 }
  validates :place, presence: true, length: { maximum: 50 }
  validates :ideal, presence: true, length: { maximum: 140 }
  validates :image_a, presence: true
  validates :image_b, presence: true
  belongs_to :user
  mount_uploader :image_a, ImageUploader
  mount_uploader :image_b, ImageUploader
  has_many :likes, dependent: :destroy
  has_many :vote_users, through: :likes, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :nickname, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
             format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password_digest, presence: true, length: { minimum: 6 }
  validates :gender, presence: true
  validates :age, presence: true
  has_many :posts
  has_many :likes, dependent: :destroy
  has_many :posts, through: :likes
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user
  
  def create
    @like = Like.new(user_id: @current_user.id, post_id: params[:post_id])
    @like.save
    redirect_to post_likes_path(params[:post_id])
  end
  
  def destroy
    @like = Like.find_by(user_id: @current_user.id, post_id: params[:post_id])
    @like.destroy
    redirect_to post_like_path(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only:[:show, :edit, :update, :destroy]
  before_action :require_login
  
  def index
    @posts = Post.all
  end
  
  def new
    if params[:back]
    @post = Post.new(post_params)
  else
    @post = Post.new
    end
  end
  
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to posts_path, notice:"投稿しました！"
    else
      render'new'
    end
  end
  
  def show
    @post = post.find(params[:id])
    @user = @post.user
    @likes_count = Like.where(post_id: @post.id).count
  end
  
  def edit
    @post = post.find(params[:id])
  end
  
  def confirm
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    render :new if @post.invalid?
  end
  
  def update
    if @post.update(post_params)
      redirect_to posts_path, notice:"投稿を編集しました！"
    else
      render 'edit'
    end
  end
  
  def destroy
    @post.destroy
    redirect_to posts_path, notice:"投稿を削除しました！"
  end
  
  private
  
  def post_params
    params.require(:post).permit(:objective, :place, :ideal, :image, :image_cache,
                                :image_a, :image_b, :image_a_cache, :image_b_cache)
  end
  
  def set_post
    @post = Post.find(params[:id])
  end
  
  def require_login
    unless logged_in?
      redirect_to new_session_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to posts_path
    else
      flash[:danger] = "ログインに失敗しました"
      render 'new'
    end
  end  
  
  def destroy
    session.delete(:user_id)
    flash[:notice]='ログアウトしました'
    redirect_to new_session_path
  end
  
  private
  
  def session_params
    params.require(:session).permit(:nickname, :email, :password,
                                          :password_confirmation)
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit, :update]
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if@user.save
      redirect_to user_path(@user.id)
    else
      render 'new'
    end
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def likes
    @user = User.find_by(id: params[:id])
    @likes = Like.where(user_id: @user.id)
  end
  
  private
  
  def user_params
    params.require(:user).permit(:nickname, :email, :password, 
                    :password_confirmation, :gender, :age,
                    :image, :image_cache)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # def current_user?(user)
  #   current_user.id == user.id
  # end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_posts_path
    elsif action_name == 'edit'
      post_path
    end
  end
  
  def likes_counter(likes)
    likes.count
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    current_user.present?
  end
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>which</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width">
  </head>
  <body>
  <header>
    <ul>
      <nav class="navbar navbar-default navbar-fixed-top">
        <!--<div class="container-fluid">-->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
              <span class="sr-only">which</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
    <ul/>        
     <a class="navbar-brand" href="#">which</a>
     </div>
     <div id="gnavi" class="collapse navbar-collapse">
      <ul class="nav bar-nav mr-auto">
      <ul class="global-nav">
  
    <% if logged_in? %>
      <li><%= link_to '投稿一覧', posts_path %></li>
  　　<li><%= link_to 'マイページ', user_path(current_user.id) %></li>
      <li><%= link_to '新規投稿', new_post_path %></li>
      <li><%= link_to 'ログアウト', session_path(current_user.id), method: :delete %></li>
        <% else %>
      <li><%= link_to '新規会員登録', new_user_path %></li>
      <li><%= link_to 'ログイン', new_session_path %></li>
        <% end %>
     </nav>
    </ul>
   <section class="main-header">
    <%= image_tag"portfolio-photo.jpg", class:"image_area" %> 
   </section>

  </header>
  
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    
    <%= yield %>
    
  <footer>
    <small>2018 sotugyo-kadai.</small>
  </footer>
  </body>
</html>

app/views/likes/_like.html.erb
<ul class="user_likes">
  <li><%= link_to("投稿", "/users/#{@user.id}") %></li>
  <li class="active"><%= link_to("投票!", "/users/#{@user.id}/likes") %></li>
</ul>

<% @likes.each do |like| %>
  <% post = Post.find_by(id: like.post_id) %>
<% end %>

app/views/likes/create.js.erb
$("#post-<%= @post.id %> .like").html("<%= escape_javascript(render "likes/like", post: @post) %>");

app/views/likes/destroy.js.erb
$("#post-<%= @post.id %> .like").html("<%= escape_javascript(render "likes/like", post: @post) %>");

app/views/posts/_form.html.erb
<%= form_with(model: @post, local: true ,url: choose_new_or_edit ) do |form| %>
 <% if @post.errors.any? %>
  <div id="error_explanation">
   <h2><%= @post.errors.count %>件のエラーがあります。</h2>
   <ul>
       
   <% @post.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
   <% end %>
   </ul>
  </div>
 <% end %>
  
  <div class="post_objective">
   <p><% form.label :objective %>目的
      <%= form.text_field :objective %>
   </p>
  </div>
  <div class="post_objective">
    <p><% form.label :place %>場所
       <%= form.text_field :place %>
    </p>
  </div>
  <div class="post_objective">
    <p><% form.label :ideal %>理想
       <%= form.text_field :ideal %>
    </p>
  </div>
  <div class="field">
   <p><% form.label :image_a %>画像A</p> 
   　　<%= image_tag(@post.image_a.url)if @post.image_a.present? %>
   　　<%= form.file_field :image_a %>
   　　<%= form.hidden_field :image_a_cache %>
   <p><% form.label :image_b %>画像B</p>
   <%= image_tag(@post.image_b.url)if @post.image_b.present? %>
   <%= form.file_field :image_b %>
   <%= form.hidden_field :image_b_cache %>
  </div>
  <div class='actions'>
   <%= form.submit %>
  </div>
<% end %>

app/views/posts/confirm.html.erb
<h3>以下の内容で送信する</h3>
<div class="form_post">
<%= form_with(model: @post, url:posts_path, local: true) do |form| %>
 <%= form.hidden_field :objective %>
 <%= form.hidden_field :place %>
 <%= form.hidden_field :ideal %>
 
 <p>目的:<%= @post.objective %></p>
 <p>場所:<%= @post.place %></p>
 <p>理想:<%= @post.ideal %></p>
 <%= image_tag(@post.image_a.url) %>
 <%= form.hidden_field :image_a_cache %>
 <%= image_tag(@post.image_b.url) %>
 <%= form.hidden_field :image_b_cache %>
 <%= form.submit "投稿する" %>
<% end %>

<%= form_with(model: @post, url:new_post_path, local: true , method: 'get') do |form| %>
 <%= form.hidden_field :objective %>
 <%= form.hidden_field :place %>
 <%= form.hidden_field :ideal %>
 <%= form.hidden_field :image_a_cache %>
 <%= form.hidden_field :image_b_cache %>
 <%= form.submit "戻る", name: 'back' %>
<% end %>
</div>

app/views/posts/edit.html.erb
<h2>投稿を作成する</h2>

<%= render 'form' %>

app/views/posts/index.html.erb
<div class="index">
<h2>投稿一覧画面(index)</h2>

<p><%= notice %></p>
 
<% @posts.each do |post| %>
 <ul class="details">
  <li>目的：<%= post.objective %></li>
  <li>内容：<%= post.place %></li>
  <li>理想：<%= post.ideal %></li>
 </ul>

 <ul class="image">
 <div class="like_a">
   <li><%= image_tag post.image_a %>
     <% if Like.find_by(user_id: @current_user.id, post_id: post.id) %>
       <%= link_to("/posts/:post_id/likes/:id", {method: "post"}) do %>
       <span class="fa fa-heart like-btn-unlike"></span>
     <% end %>
     <% else %>
       <%= link_to("/posts/:post_id/likes", {method: "post"}) do %>
       <span class="fa fa-heart like-btn-like"></span>
       <% end %>
     <% end %>
   <%= @likes_count %>
 </div>
 <div class="like_b">
   <%= image_tag post.image_b %></li>
     <% if Like.find_by(user_id: @current_user.id, post_id: post.id) %>
       <%= link_to("/posts/:post_id/likes/:id", {method: "post"}) do %>
       <span class="fa fa-heart like-btn-unlike"></span>
     <% end %>
     <% else %>
       <%= link_to("/posts/:post_id/likes", {method: "post"}) do %>
       <span class="fa fa-heart like-btn-like"></span>
       <% end %>
     <% end %>
   <%= @likes_count %>
 </div>
   </li>
 </ul>
 <ul class="menu">
   <% if post.user_id == @current_user.id %>
   <li><%= link_to '詳細画面へ', post_path(post.id) %></li>
   <li><%= link_to '投稿を編集する', edit_post_path(post.id), data: { confirm: '本当に編集していいですか？' } %></li>
   <li><%= link_to '投稿を削除する', post_path(post.id), method: :delete, data: { confirm: '本当に削除していいですか？' } %></li>
   <!--<li><!%= link_to '新規投稿する', new_post_path %></li><br>-->
   <% end %>
</ul>
<% end %>
</div>

app/views/posts/new.html.erb
<h2>投稿を作成する</h2>

<%= render 'form' %>

app/views/posts/show.html.erb
<h1>Post詳細画面</h1>
<p>目的:<%= @post.objective %></p>
<p>場所:<%= @post.place %></p>
<p>理想:<%= @post.ideal %></p>
<p><%= image_tag @post.image_a.url %><%= image_tag @post.image_b.url %></p>

<%= link_to 'Back', posts_path %>

app/views/tops/index.html.erb
<div id="wrap">
  <div class="content">
    <div class="main_center">
      <section class="about cleafix">
      <h2>About</h2>
        <div class="about_text">
          <p><strong>どっちを着ようか決められない・・
          <br>どっちの方が素敵に見えるかな？？
          </strong><br>
          <br>そんなお悩みありませんか？
          <br>
          <br>当サイトはそんなお悩みの方のための
          <br>お助けアプリケーションです。
          <br>
          <br>2枚のコーディネート写真を投稿し
          <br>どっちがいいかみんなに投票してもらいましょう！
          </p>
        </div>
      <br><h3>サイトのご利用方法について</h3>
        <div class="step">
          <p>当サイトは会員登録者のみご利用が可能です。(無料）
          <br>トップページのヘッダーにある「新規会員登録」をクリックし、
          <br>情報入力画面に従い必要項目を入力してください。
          <br>登録完了後、ログイン画面よりお進み下さい。
          </p>
        </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="user_new">
<h2>新規会員登録</h2><br>
<%= form_with(model: @user, local: true) do |f| %>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
   
  <p><% f.label :nickname %>ニックネーム</p>
  <p><%= f.text_field :nickname %></p>

  <p><% f.label :email %>メールアドレス</p>
  <p><%= f.email_field :email %></p>
   
  <p><% f.label :password %>パスワード(6文字以上)</p>
  <p><%= f.password_field :password %></p>
 
  <p><% f.label :password_confirmation %>パスワード再入力</p>
  <p><%= f.password_field :password_confirmation %></p>
  
  <p><% f.label :gender %>性別</p>
  <p><%= f.text_field :gender %></p>
  
  <p><% f.label :age %>歳</p>
  <p><%= f.number_field :age %></p>
  
  <p><% f.label :image %>プロフィール写真</p>
  <p><%= f.file_field :image %></p><br>
  
<div class="inputbutton">
  <%= f.submit "この内容で登録する" %>
</div>
<% end %>
</div>

app/views/users/show.html.erb
<h1><%= @user.nickname %>さんのページ</h1>

 <p>ニックネーム：<%= @user.nickname %>さん</p>

 <p>メールアドレス：<%= @user.email %></p>

 <p>性別：<%= @user.gender %></p>

 <p>年齢：<%= @user.age %>歳</p>

 <p>プロフィール写真：<%= image_tag(@user.image.url) if @user.image.url %></p>